### ISSUE TITLE
ubuntu+firefox does not render colors in legend

### ISSUE THREAD

**Issue by spacemonkey** [dwolfand/pay-it-furloughed-trender#2]
Take a look at the attached screenie, the chart renders fine but the legend just renders black dots.
![screenshot from 2019-01-17 16-25-04](https://user-images.githubusercontent.com/93724/51349917-da269180-1a74-11e9-8d00-de3e329090b4.png)

**Comment by dschep** [comment]
Similarly in Firefox on MacOS 
![image](https://user-images.githubusercontent.com/667763/51350110-5620d980-1a75-11e9-8a09-6187a18d4ae2.png)

**Comment by dwolfand** [comment]
@spacemonkey Thanks! This was fixed with #4
